# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Георгий\Desktop\ФТИ\RotationAndDeposition\profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Profile(object):
    def setupUi(self, Profile):
        Profile.setObjectName("Profile")
        Profile.resize(800, 600)
        Profile.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Profile)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot_widget = QtWidgets.QWidget(self.centralwidget)
        self.plot_widget.setMinimumSize(QtCore.QSize(500, 250))
        self.plot_widget.setObjectName("plot_widget")
        self.plot_layout = QtWidgets.QVBoxLayout(self.plot_widget)
        self.plot_layout.setObjectName("plot_layout")
        self.verticalLayout.addWidget(self.plot_widget)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.in_slider_R = QtWidgets.QSlider(self.widget)
        self.in_slider_R.setOrientation(QtCore.Qt.Horizontal)
        self.in_slider_R.setObjectName("in_slider_R")
        self.horizontalLayout.addWidget(self.in_slider_R)
        self.verticalLayout.addWidget(self.widget)
        Profile.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Profile)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Profile.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Profile)
        self.statusbar.setObjectName("statusbar")
        Profile.setStatusBar(self.statusbar)
        self.actionExport_data = QtWidgets.QAction(Profile)
        self.actionExport_data.setObjectName("actionExport_data")
        self.menu.addAction(self.actionExport_data)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Profile)
        QtCore.QMetaObject.connectSlotsByName(Profile)

    def retranslateUi(self, Profile):
        _translate = QtCore.QCoreApplication.translate
        Profile.setWindowTitle(_translate("Profile", "MainWindow"))
        self.label.setText(_translate("Profile", "R"))
        self.menu.setTitle(_translate("Profile", "File"))
        self.actionExport_data.setText(_translate("Profile", "Export data"))
