# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Георгий\Desktop\ФТИ\RotationAndDeposition\gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1349, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.InputWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.InputWidget.setMinimumSize(QtCore.QSize(851, 631))
        self.InputWidget.setObjectName("InputWidget")
        self.Model = QtWidgets.QWidget()
        self.Model.setObjectName("Model")
        self.gridLayout = QtWidgets.QGridLayout(self.Model)
        self.gridLayout.setObjectName("gridLayout")
        self.source_plot = QtWidgets.QWidget(self.Model)
        self.source_plot.setMinimumSize(QtCore.QSize(400, 300))
        self.source_plot.setMaximumSize(QtCore.QSize(600, 450))
        self.source_plot.setObjectName("source_plot")
        self.source_plot_vl = QtWidgets.QVBoxLayout(self.source_plot)
        self.source_plot_vl.setObjectName("source_plot_vl")
        self.gridLayout.addWidget(self.source_plot, 1, 1, 1, 1)
        self.table_settings = QtWidgets.QTableView(self.Model)
        self.table_settings.setMinimumSize(QtCore.QSize(500, 550))
        self.table_settings.setAlternatingRowColors(False)
        self.table_settings.setObjectName("table_settings")
        self.gridLayout.addWidget(self.table_settings, 0, 0, 1, 1)
        self.mesh_plot = QtWidgets.QWidget(self.Model)
        self.mesh_plot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mesh_plot.sizePolicy().hasHeightForWidth())
        self.mesh_plot.setSizePolicy(sizePolicy)
        self.mesh_plot.setMinimumSize(QtCore.QSize(400, 300))
        self.mesh_plot.setMaximumSize(QtCore.QSize(600, 450))
        self.mesh_plot.setObjectName("mesh_plot")
        self.mesh_plot_vl = QtWidgets.QVBoxLayout(self.mesh_plot)
        self.mesh_plot_vl.setObjectName("mesh_plot_vl")
        self.gridLayout.addWidget(self.mesh_plot, 0, 1, 1, 1)
        self.update_model_Button = QtWidgets.QPushButton(self.Model)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_model_Button.sizePolicy().hasHeightForWidth())
        self.update_model_Button.setSizePolicy(sizePolicy)
        self.update_model_Button.setObjectName("update_model_Button")
        self.gridLayout.addWidget(self.update_model_Button, 2, 0, 1, 1)
        self.InputWidget.addTab(self.Model, "")
        self.Deposition = QtWidgets.QWidget()
        self.Deposition.setObjectName("Deposition")
        self.DepositionButton = QtWidgets.QPushButton(self.Deposition)
        self.DepositionButton.setGeometry(QtCore.QRect(20, 170, 112, 34))
        self.DepositionButton.setObjectName("DepositionButton")
        self.film_plot = QtWidgets.QWidget(self.Deposition)
        self.film_plot.setGeometry(QtCore.QRect(460, 20, 400, 300))
        self.film_plot.setMinimumSize(QtCore.QSize(400, 300))
        self.film_plot.setObjectName("film_plot")
        self.film_vl = QtWidgets.QVBoxLayout(self.film_plot)
        self.film_vl.setContentsMargins(0, 0, 0, 0)
        self.film_vl.setObjectName("film_vl")
        self.R_Slider = QtWidgets.QSlider(self.Deposition)
        self.R_Slider.setGeometry(QtCore.QRect(50, 30, 160, 21))
        self.R_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.R_Slider.setObjectName("R_Slider")
        self.k_Slider = QtWidgets.QSlider(self.Deposition)
        self.k_Slider.setGeometry(QtCore.QRect(50, 70, 160, 22))
        self.k_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.k_Slider.setObjectName("k_Slider")
        self.NR_Slider = QtWidgets.QSlider(self.Deposition)
        self.NR_Slider.setGeometry(QtCore.QRect(50, 110, 160, 22))
        self.NR_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.NR_Slider.setObjectName("NR_Slider")
        self.label = QtWidgets.QLabel(self.Deposition)
        self.label.setGeometry(QtCore.QRect(20, 30, 21, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Deposition)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 16, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Deposition)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 21, 19))
        self.label_3.setObjectName("label_3")
        self.lcd_R = QtWidgets.QLCDNumber(self.Deposition)
        self.lcd_R.setGeometry(QtCore.QRect(220, 30, 64, 23))
        self.lcd_R.setSmallDecimalPoint(True)
        self.lcd_R.setObjectName("lcd_R")
        self.lcd_k = QtWidgets.QLCDNumber(self.Deposition)
        self.lcd_k.setGeometry(QtCore.QRect(220, 70, 64, 23))
        self.lcd_k.setObjectName("lcd_k")
        self.lcd_NR = QtWidgets.QLCDNumber(self.Deposition)
        self.lcd_NR.setGeometry(QtCore.QRect(220, 100, 64, 23))
        self.lcd_NR.setObjectName("lcd_NR")
        self.R_disp = QtWidgets.QLineEdit(self.Deposition)
        self.R_disp.setGeometry(QtCore.QRect(290, 30, 51, 25))
        self.R_disp.setObjectName("R_disp")
        self.k_disp = QtWidgets.QLineEdit(self.Deposition)
        self.k_disp.setGeometry(QtCore.QRect(290, 70, 51, 25))
        self.k_disp.setObjectName("k_disp")
        self.NR_disp = QtWidgets.QLineEdit(self.Deposition)
        self.NR_disp.setGeometry(QtCore.QRect(290, 100, 51, 25))
        self.NR_disp.setObjectName("NR_disp")
        self.InputWidget.addTab(self.Deposition, "")
        self.horizontalLayout.addWidget(self.InputWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1349, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.InputWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.update_model_Button.setText(_translate("MainWindow", "обновить модель"))
        self.InputWidget.setTabText(self.InputWidget.indexOf(self.Model), _translate("MainWindow", "Модель"))
        self.DepositionButton.setText(_translate("MainWindow", "Deposition"))
        self.label.setText(_translate("MainWindow", "R"))
        self.label_2.setText(_translate("MainWindow", "k"))
        self.label_3.setText(_translate("MainWindow", "NR"))
        self.InputWidget.setTabText(self.InputWidget.indexOf(self.Deposition), _translate("MainWindow", "Deposition"))

